name: Testgo ve

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run minio
        run: >
          mkdir -p export/objectstoragetest &&
          mkdir -p export/.minio.sys/buckets/objectstoragetest &&
          docker run -d -p 9000:9000 --name minio
          -e "MINIO_ROOT_USER=minioadminuser"
          -e "MINIO_ROOT_PASSWORD=minioadminpassword"
          -v $(pwd)/export:/export
          minio/minio server /export

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Get dependencies
        run: go get -v -t -d ./...g

      - name: Test code
        run: go test -v ./...
        env:
          MINIO_HOST: localhost
