name: s3-local

on:
  push:
    branches:
      - main

jobs:
  s3:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=ABCDEFGHIJKLMN" \
                     -e "MINIO_SECRET_KEY=ABCDEFGHI" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data
      - name: check s3 command
        env:
          AWS_ACCESS_KEY_ID: "ABCDEFGHIJKLMN"
          AWS_SECRET_ACCESS_KEY: "ABCDEFGHI"
        run: |
          echo "this is test file" > ~/test.txt
          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://objectstoragetest # make bucket
          aws --endpoint-url http://127.0.0.1:9000/ s3 ls
          aws --endpoint-url http://127.0.0.1:9000/ s3 cp ~/test.txt s3://objectstoragetest # cp

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: build
        run: go install ./...

      - name: test
        run: ./tests/execute_all_tests.sh        
        env:
          OBJECTSTORE_ENDPOINT: http://localhost:9000
